LOAD DATA 
 INFILE mocities.dat
 TRUNCATE
 CONTINUEIF NEXT(1:1) = '#'
 INTO TABLE MOCITIES
 FIELDS TERMINATED BY '|'
 TRAILING NULLCOLS (
   CITY 	NULLIF CITY = BLANKS,
   LAT,
   LON,
   LOCATION COLUMN OBJECT 
   (
     SDO_GTYPE       INTEGER EXTERNAL, 
     SDO_SRID        INTEGER EXTERNAL, 
     SDO_POINT COLUMN OBJECT
       (X            FLOAT EXTERNAL, 
        Y            FLOAT EXTERNAL) 
   )
)
